sonar.organization=camilo-h
sonar.projectKey=Camilo-H_DeporteParaTodosFront

sonar.sources=src
sonar.exclusions=**/node_modules/**,**/*.spec.ts,**/*.d.ts
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.coverage.exclusions=**/*.spec.ts

sonar.javascript.lcov.reportPaths=coverage/deporte-para-todos/lcov.info
sonar.typescript.tsconfig=tsconfig.json

sonar.sourceEncoding=UTF-8
